/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author MoaathAlrajab
 */
public class Homework09 {
    
    
    
    
    public static void main(String[] args){
        //set variabels
        //set num rows
        int n=7;
        int sum=0;
        
        //loop for each iteration of row
        for(int i=1; i<=n; i++) {
            //add current number to the sum
            sum += i;
            //look at the colums in the current row
            for(int j=1; j<=i; j++){
                //Output
                System.out.print(sum-(i-j)+" ");
            }
            //New line
            System.out.println();
        }
    }
    // ToDo 01:  Write an algorithm to solve the following problem
    /*
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over one hundred divisors?
    
-----Ans: 73920 would be the number for one hundred divisors.-----
    
    
    */
    
    
}
